# .github/release.yml

changelog:
  exclude:
    labels:
      - wontfix
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
